sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t ubnt-erpro-shadowsocks-libev .
  
script:
  - docker run -it -v $(pwd):/usr/local/ss ubnt-erpro-shadowsocks-libev
