name: Master-CI

on:
  push:
    branches:
      - mips64

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      run: docker build . -t ss-libev-mips
    - name: Build Shadowsocks-libev using docker image
      run: docker run -i -v $(pwd):/usr/local/ss ss-libev-mips
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with: 
        name: ss-libev-mips64
        path: ./erx/
